### ISSUE TITLE
Замечания по 8.1

### ISSUE THREAD

**Issue by sergey-shambir** [AnatolyKorablyov/TP_lab_8.1#1]
Самая главная проблема: сейчас вращение колёс (в градусах) равно пройденному расстоянию (в пикселях). В реальности они должны быть линейно зависимы - иначе колесо будет визуально проскальзывать при любом изменении размера колеса.

Решается проблема просто: по диаметру колеса (а диаметр колеса - это размер спрайта) рассчитать длину окружности колеса, и пройденное расстояние делить на длину окружности. Это и будет число поворотов колеса (возможно, нецелое). Умножив число оборотов на 360 (градусов), мы получим градусы.

- ряд функций станет проще, если пару (x, y) позиции машины заменить на sf::Vector2f.
- функция start_move_time должна тоже принимать три части машины по ссылке, а лучше и вовсе создать структуру данных CarSprites или CarUnit. Переменную rotation можно, кстати, переместить в поле wheelsRotation этой структуры.
- к созданной структуре можно добавить функции set_car_wheel_rotation и set_car_position, чтобы устанавливать вращение обоих колёс или положение машины в один вызов
- не надо объявлять несколько переменных на одной строке, как в ```Sprite bodyCar, leftWheel, rightWheel;```

**Comment by AnatolyKorablyov** [comment]
исправил

**Comment by sergey-shambir** [comment]
Принято
